#!/bin/bash

echo "        **************************************** "
echo "        **************************************** "  
echo "        **                 ~;                 ** "       
echo "        **                ,/|\,               ** "   
echo "        **               ,/' |\ \,            ** "
echo "        **              ,/'   | |  \          ** "
echo "        **             ,/'     | |   |        ** "
echo "        **           ,/'       |/    |        ** "
echo "        **         ,/__________|-----' ,      ** "
echo "        **       ___.....-----''-----/        ** " 
echo "        **        \  Nino_Script    /         ** "
echo "        **   ~~-~^~^~~'~~^^~^~-'^~^~^'~-~^~^  ** "
echo "        **   ~-^'~^-~^~-^~^'^~^-^~^'^~^-~^    ** "
echo "        **           [0] cluar                ** "
echo "        **           [1] helipacity           ** "
echo "        **           [2] netbase              ** "
echo "        **           [3] cluarnino            ** "               
echo "        **           [4]                      ** "
echo "        **         ► [5] fullstack            ** "
echo "        **           [6]                      ** "
echo "        **           [7]                      ** "
echo "        **           [8]                      ** "
echo "        **           [9]                      ** "
echo "        **          [10] Udemy                ** "
echo "        **          [11] Bootcamp Netuno      ** "
echo "        **          [12]                      ** "
echo "        **          [13]                      ** "
echo "        **          [14]                      ** "
echo "        **                                    ** "
echo "        **      CTRL + C ==>SAIR              ** "
echo "        **                                    ** "
echo "        **************************************** " 
echo "        **     Good job!! Nino ;-)            ** "
echo "        **************************************** "
echo "        **************************************** "










echo Digite o numero do projeto:
read numero
if     [ $numero == "0" ] 
then 
    echo "Atenção no Cluar sou colaborador!!!"
elif [ $numero == "1" ] 
then
    echo "Ótimo voce escolheu helipacity"
elif [ $numero == "2" ] 
then
    echo "Ótimo voce escolheu netbase"
elif [ $numero == "3" ]
then 
    echo "Ótimo voce escolheu o cluarnino"
elif [ $numero == "4" ]
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "5" ] 
then
    echo "Ótimo voce escolheu fullstack"
elif [ $numero == "6" ]
then 
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "7" ]  
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "8" ] 
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "9" ]
then 
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "10" ]
then
    cd Dev
    cd udemy
    code .  
    firefox https://www.udemy.com/course/curso-web/learn/
elif [ $numero == "11" ] 
then
    
    # firefox https://dev.netuno.org/formation/3afd971f-dace-4dd2-adb2-1382d5cac494
    
    ssh luismijias@bootcamp.dev.netuno.org -p 20122
   
    
elif [ $numero == "12" ]
then x
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "13" ]
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "14" ] 
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
else
 echo "Comando inválido :-\.Digite o número de um dos projetos acima ;-)."
fi




#**********Parte do cliente(pc)**********
#comando para entrar sem senha no ssh
#vídeo auxilio https://www.youtube.com/watch?v=wSOAdqnYjeY
#Obs: dentro da pasta .ssh --> scp -P 20122 id_rsa.pub luismijias@135.181.217.178:~/.ssh/authorized_keys

#******Parte do servidor******** 
# crie o diretório --> mkdir .ssh
#crie o arquivo dentro da pastar .ssh --> touch authorized_keys
#$dê a autorização correta--> chmod 600 ~/.ssh/authorized_keys
#depois envie o arquivo do pc para o sevidor.
#$ sudo systemctl restart ssh
#https://linuxhint.com/configure-authorized-keys-ssh-ubuntu

